In [ ]:
import numpy as np

# Accessing and manipulating arrays

In the previous notebook we explored the creation of NumPy arrays. Now we'll
learn how to access and manipulate elements within arrays, and also
how to extract specific elements out of arrays.

## $ \S 1 $ Accessing and modifying individual array elements

Recall that lists in Python are __mutable__, meaning that we may modify
the individual elements of a list:

In [ ]:
primes = [199, 1_999, 19_999]
primes[2] = 19
print(primes)

In contrast, a Python tuple is __immutable__. We can still access its
elements through `[]`, but we can't modify them:

In [ ]:
fruits = ('🍎', '🍊', '🍍')
print(fruits[0])

In [ ]:
fruits[0] = '🍉'

NumPy arrays are also mutable, like lists. Consider the following vector $ \mathbf{a} $:

In [ ]:
a = np.array([1, 2, 3])
print(a)

To access or modify the $ 0 $-th element of $ \mathbf a $ (recall that we always
count from $ 0 $ in Python), we use the same syntax as we would if it were a
list:

In [ ]:
print(a[0])  # Access 0-th element of `a`
a[0] = -1    # Modify this element
print(a)     # Print the result

If we are dealing with a $ 2D $ array, we use `[i, j]` to access its $ (i, j)
$-th entry, that is, the element in row $ i $ and column $ j $.

__Exercise:__ Modify the off-diagonal elements in the following matrix $ A $ to
turn it into the $ 2 \times 2 $ identity matrix.

In [ ]:
A = np.ones((2, 2))
print("Before modifications:")
print(A, '\n')

# ...
# ...
print("After modifications:")
print(A)

In general, when dealing with an $ n $-dimensional array, use
`[k_1, k_2, ..., k_n]` to access the element having indices
$ k_1, k_2, \cdots, k_n $, respectively.

__Exercise:__ Build a $ 3D $ identity array $ M $ of shape $ (5, 5, 5) $ by
first populating it with zeros, then setting all elements whose indices
have the form $ (i, i, i) $ to $ 1 $ in the following two ways: 

(a) Using a `for` loop.

(b) With the single call `fill_diagonal(M, 1)`.

In [ ]:
# Populate M with zeros:
# M = ...

# Set diagonal elements equal to 1:
# ...

# Print the result:
# print(M)


Like Python lists, NumPy arrays support negative indexing. The index $ -1 $
refers to the last element, $ -2 $ to the second-to-last, and so on:

__Exercise:__ Modify the last coordinate of the vector
$ \mathbf{v} \in \mathbb{R}^6 $ below so that its length becomes $ 3 $. _Hint:_
Recall that the norm (length) of a vector $ \mathbf{v} = (v_1, v_2, \cdots, v_n) $
in $ \mathbb{R}^n $ is given by $ \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2} $.

In [ ]:
v = np.array([1, 1, 1, 1, 1, 1])

print(f"Vector: {v}")
print(f"Norm of v = {np.linalg.norm(v):.3f}")

Negative indexing works with multi-dimensional arrays as well:

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A[-1, -1])  # Bottom-right element (value: 9)
print(A[-2, -3])  # Element at second-to-last row, third-to-last column (value: 4)

__Exercise:__ Given the $ 3D $ array below, access and print:

(a) The element at position $ (0, 1, 1) $.

(b) The last element of the entire array.

(c) The element at row $ 0 $, column $ 1 $ of "layer" $ 2 $.

In [10]:
B = np.array([[[1, 2], [3, 4]], 
              [[5, 6], [7, 8]], 
              [[9, 10], [11, 12]]])
print(B)
# (a)

# (b)

# (c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## $ \S 2 $ Slicing $ 1D $ arrays

__Slicing__ is an operation that allows us to extract a subarray from an array.
The syntax for $ 1D $ arrays is exactly the same as for slices of Python lists,
namely, `a[start:stop:step]`, where `a` denotes an array and:

* `start` is the index where the slice begins (included).
* `stop` is the index where the slice ends (excluded).
* `step` is the step size between elements.

If any of these are omitted, they default to their natural boundaries (start of
the array, end of the array, and step size $ 1 $).

__Exercise:__ Let $ \mathbf a = (0, 1, \cdots, 10) $.

(a) Instantiate this array using `arange` or with `linspace` together with the instruction `a.astype(int)`.

(b) Take a slice of $ \mathbf a $ resulting in $ (0, 1, \cdots, 4) $.

(c) Slice $ \mathbf a $ to obtain the array $ (5, 6, \cdots, 10) $.

(d) Construct a slice to retrieve the subarray $ (3, 5, 7, 9) $.

(e) Obtain a new array consisting of all elements of $ \mathbf a $ in reverse order.

(f) Take a full slice of $ \mathbf a $, call it $ \mathbf b $, and modify its $ 0
$-th element. Is $ \mathbf a $ affected?

As seen in the previous exercise, _slicing an array only creates a view of
the original array, not a copy_.  A __view__ is a new array object that refers to
the same data as the original array.  This means that:
* Changes made through the view affect the original array, and vice versa.
* No memory duplication occurs when creating a view.

This behavior is by design, for efficiency reasons.

In [22]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]  # This creates a view, not a copy
print("Original a:", a)
print("View b:      ", b)

b[0] = 8  # Modifying the view
print("After modifying b, a becomes:", a)

Original a: [1 2 3 4 5]
View b:       [2 3 4]
After modifying b, a becomes: [1 8 3 4 5]


📝 To create a copy rather than a view in NumPy, use the `copy()` method:

In [18]:
a = np.array([1, 2, 3, 4, 5])
c = a.copy()  # This creates an explicit copy
c[1] = 8

print("Copy c:    ", c)
print("Original a:", a)  # Remains unchanged

Copy c:     [1 8 3 4 5]
Original a: [1 2 3 4 5]


__Exercise:__ Create a vector $ \mathbf{a} = (1, 2, 3) $ and a full slice $
\mathbf{b} $ of $ \mathbf{a} $. Check whether $ \mathbf{a} $ and
$ \mathbf{b} $ point to the same data with `np.shares_memory(a, b)`.

⚠️⚡ Note in contrast that slices of Python lists or tuples _are_ independent
copies from their originals. However, these are _shallow_ copies: only
the containers themselves are copies, not their elements. This may lead to
unexpected behavior, as in the following example:

In [20]:
original = [[1, 2, 3], [4, 5, 6]]
shallow1 = original[:]
shallow2 = original[:]

shallow1[0] = [-1, -2, -3]
print(original)  # original is not affected

shallow2[0][0] = 8
print(original)  # original is affected!

[[1, 2, 3], [4, 5, 6]]
[[8, 2, 3], [4, 5, 6]]


## $ \S 3 $ Slicing general arrays

Slicing becomes more interesting with higher-dimensional arrays. For a $ 2D $
array, in principle we need to specify slices for both dimensions, separated by
a comma. If we use a single slice, then we are indexing into full rows.

In [24]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(M, '\n')

# Accessing a specific row:
print(M[1, :], '\n')  # "First" row

# Accessing a specific column:
print(M[:, 2], '\n')  # "Second" column

# Sub-array slicing:
print(M[0:2, 1:3], '\n')  # Top right 2x2 sub-array

# If we use only one slice, then entire rows are extracted:
print(M[0:2])  # First 2 rows

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5 6] 

[3 6 9] 

[[2 3]
 [5 6]] 

[[1 2 3]
 [4 5 6]]


__Exercise:__ 
Given the $ 3 \times 4 $ matrix below, use slicing to extract:


<img src="notebook_2_slicing.png" alt="Slicing exercise" width="870" height="174">

(a) The first two rows.

(b) The last two columns.

(c) A $ 2 \times 2 $ submatrix containing the elements at the intersection of
    the last two rows and the first two columns.

In [ ]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
# (a)

# (b)

# (c)

All of the principles we have seen extend to arrays of higher dimensions.

__Exercise:__ Consider a $ 3D $ array representing an RGB image of shape
($ 3 $, height, width). Write slices to:

(a) Extract the green channel only (index $ 1 $ in the $ 0 $-th dimension).

(b) Get the top-left $ 50 \times 50 $ pixel region of the image.

(c) Downsample the image by taking every second pixel in both height and width
    dimensions.

In [ ]:
# Let's create a random low-resolution image with 3 channels (R, G and B)
# with 8 bits = 256 values per channel (color intensities between 0 and 255):
image = rng.integers(0, 256, size=(3, 1280, 720))
# (a)

# (b)

# (c)

## $ \S 4 $ Other types of indexing

Let's now consider a couple of additional indexing mechanisms that allow for
more flexible selections and manipulations of arrays.

### $ 4.1 $ Integer array indexing

__Integer array indexing__ allows us to use arrays (or lists) of indices to
select elements:

In [ ]:
a = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])  # Select elements at indices 0, 2, and 4
print(a[indices])

[10 30 50]


For multi-dimensional arrays, we can select specific combinations of rows and columns:

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Select diagonal elements:
rows = [0, 1, 2]  # here we are using a _list_ (not array) of indices
cols = [0, 1, 2]
print(A[rows, cols])

[1 5 9]


Note how the indices for the rows and columns are paired in order, instead of
being combined in all possible ways.

__Exercise:__ For the same matrix $ A $ as above, use integer array indexing
to select the elements in the anti-diagonal.

In [ ]:
# Select elements (0,2), (1,0), (2,1) (the anti-diagonal):
rows = # ...
cols = # ...
print(A[rows, cols])

[3 4 8]


__Exercise:__ Given the $ 4 \times 4 $ matrix below, use integer array indexing
to:

(a) Extract the four corner elements.

(b) Extract the elements on both diagonals (main diagonal and anti-diagonal).

In [78]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(M)
# (a)

# (b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### $ 4.2 $ Combining different types of indices

We can mix different types of indices (slices, integers, arrays) to create more
complex selections.

In [28]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(M)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


One alternative is to specify a list of the indices that we want to index into
for some of the dimensions.  This allows us to capture sets of indices that do
not follow the pattern of a slice.

In [29]:
# Select rows 0, 1 and 3, all columns:
print(M[[0, 1, 3], :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]


In [87]:
# Select all rows, columns 1 and 3:
print(M[:, [1, 3]], '\n')

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]] 



If instead of using a slice or list of indices, we specify a single index for
some dimension, then that dimension "collapses". In particular, the resulting
array will have a smaller rank. This is illustrated by the following example:

In [ ]:
# Extracting row 1 through a double slice:
print(M[1:2, :])  # The result is still a 2D array

# Extracting row 1 by indexing into it:
print(M[1, :])  # The result is a 1D array

__Exercise:__ Create a $ 2D $ array of shape $ (4, 4) $ filled with
random integers and print it for reference.

(a) Extract the last row to produce a $ 1D $ array.

(b) Extract the last column, as a $ 2D $ array.

(c) Extract a $ 2\times 2 $ sub-array from the center of this array.

(d) Extract the $ 3 \times 2 $ lower-left corner of the array.

(e) Extract the subarray consisting of columns indexed by $ 1 $ and $ 3 $
    in two ways: by using a slice with step size $ 2 $ and by using a list of
    indices.

## $ \S 5 $ Boolean indexing

### $ 5.1 $ Creating boolean masks and filtering arrays with masks

__Boolean indexing__ is a powerful feature that allows us to select elements
from an array based on _conditions_.  First we create a __boolean mask__, i.e., an
array of `True` and `False` values, having the same shape as the original array.
Then we use this mask to filter elements out of our array. Here's an example:


<img src="notebook_2_boolean_indexing.png" alt="Boolean indexing" width="287" height="381">

In [101]:
v = np.array([1, 2, 3, 4, 5])
print("Original array:", v)

# Create a boolean mask:
mask = v > 2
print("Filter: ", mask)

# Use boolean indexing to filter the elements that are greater than 2:
selected_elements = v[mask]
print("Selected elements:", selected_elements)

Original array: [1 2 3 4 5]
Filter:  [False False  True  True  True]
Selected elements: [3 4 5]


In NumPy, and Python in general, the boolean value `True` is treated as
equivalent to $ 1 $ in numerical contexts, and `False` is equivalent to
$ 0 $. Thus, in the preceding example, we can compute the number of elements
greater than $ 2 $ by taking the sum of the entries in the filter (we will
return to the `np.sum` function later):

In [ ]:
print("# of elements greater than two:", np.sum(filter))

We can also filter elements in one step; this syntax is very common in the
NumPy ecosystem, although it may seem somewhat strange when one first encounters it:

In [ ]:
u = np.array([-3, -2, -1, 0, 1, 2, 3])
result = u[u <= 0]
print(result)

[-3 -2 -1  0]


__Exercise:__ Consider the matrix $ A $ given below.

(a) Extract its elements that are $ \ge 2 $ using boolean indexing.

(b) What is the shape of your mask? What is the shape of the resulting array? In
    what order are the elements filtered?

In [110]:
A = rng.integers(0, 5, size=(3, 4))
print(A)

[[2 2 1 3]
 [1 1 4 1]
 [1 3 3 0]]


📝 When using boolean indexing on a multi-dimensional array, the result is
always a $ 1D $ array containing the elements where the mask is true.

⚠️ Boolean indexing always generates a new array, even when the result is otherwise identical to the original array: 

In [99]:
v = np.array([1, 2, 3, 4, 5])
u = v[v > 0]  # Filters the elements of v > 0, which happens to be all of v

# Checking the memory addresses of u and v to see whether they match:
print(id(u))
print(id(v))

132963600191760
132963599791184


### $ 5.2 $ Combining boolean operations

We can craft more complex masks by using the familiar boolean operators
__negation__, __and__, __or__ and __exclusive or__ (__xor__). However, the Python
versions of the first three, `not`, `and`, `or`, respectively, do not work with
boolean arrays. Instead, we should use `~`, `&` and `|`, respectively. The
xor operator is denoted by `^`.

<img src="notebook_2_truth_tables.png" alt="Truth tables" width="752" height="168">

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Select elements greater than 2 AND less than 7:
print(a[(a > 2) & (a < 7)])  # Result: [3, 4, 5, 6]

# Select elements less than 3 OR greater than 7:
print(a[(a < 3) | (a > 7)])  # Result: [1, 2, 8, 9]

# Negate a condition with ~:
print(a[~(a % 3 == 0)])  # Select numbers NOT divisible by 3: [1, 2, 4, 5, 7, 8]

# Extract all numbers that multiples of 2 OR 3, but NOT multiples of 6:
print(a[(a % 2 == 0) ^ (a % 3 == 0)])

[3 4 5 6]
[1 2 8 9]
[1 2 4 5 7 8]
[2 3 4 8 9]


📝 Make sure to put parentheses around each condition when combining it.

Given the array below, use boolean indexing to extract:

(a) Numbers that are both positive and even.

(b) Numbers that are either negative or greater than $ 20 $.

(c) Numbers that are either odd or positive, but not both.

In [114]:
data = np.array([15, 23, -10, 0, 42, -7, 8, 12, -25, 30])

Here's a more interesting example. Consider a workplace where employees log
their daily hours. Consider the problem of retrieving the instances where
one of the employees worked overtime. The information is stored over two arrays:
* A $ 1D $ array `names` containing the names of five employees.
* A $ 2D $ array `hours` whose $ i $-th row corresponds to the $ i $-th employee
  listed in `names`, and whose columns correspond to the number of hours worked over two weeks.

In [ ]:
# Names of employees:
names = np.array(["Alice", "Bob", "Carol", "Dave", "Alice", "Carol", "Dave", "Bob"])

# Array of hours worked each day for two weeks:
hours = np.array([
    [9, 8, 10, 8, 7],  # Alice, week 1
    [7, 8, 9, 8, 6],   # Bob, week 1
    [10, 7, 12, 8, 9], # Carol, week 1
    [6, 5, 7, 6, 8],   # Dave, week 1
    [8, 9, 7, 10, 8],  # Alice, week 2
    [8, 9, 10, 8, 10], # Carol, week 2
    [8, 9, 7, 8, 7],   # Dave, week 2
    [7, 8, 6, 5, 9]    # Bob, week 2
])

We can extract all of the hours worked by Carol during these two weeks by:
* Creating a boolean filter `names == "Carol"`.
* Using this to index into `hours`, more precisely its rows.

In [ ]:
# Filter to select rows for a specific employee, Carol:
mask = (names == "Carol")
hours_Carol = hours[mask]
print(hours_Carol)

Now we can use another filter to obtain the times when Carol worked overtime
(and the corresponding hours). Note that the result is a $ 1D $ array:

In [ ]:
overtime_Carol = hours_Carol[hours_Carol > 8]
print(overtime_Carol)

__Exercise:__ Referring to the preceding example, extract:

(a) The overtime hours worked by Alice or by Bob.

(b) The numbers of hours between $ 7 $ and $ 9 $ worked by anyone except Dave.

__Exercise:__ You're provided below with a dataset `rainfall_data` of daily
rainfall measurements (in millimeters) in a city for four months (June to
September), stored as a $ 2D $ NumPy array.  Each row represents a month, and each
column represents a day.

(a) Compute the average rainfall and the standard deviation of the sample
across the entire period using the functions `np.mean` and `np.std`.

(b) Identify days with above-average rainfall for each month, and calculate the
percentage of such days in each month. _Hint:_ Use a for loop to iterate over
each month/row of the dataset. Use a Boolean filter to find which days
had greater than average rainfall and take the sum of the `True` values
as discussed above to compute the percentages. 

In [ ]:
np.random.seed(123456789)

# Sample mean and standard deviation for each month (in mm):
mean_rainfall = [1.5, 2.7, 2.7, 0.9]  # Average daily rainfall (mm) for June, July, August, September
std_deviation = [1.5, 2, 2.5, 1.5]  # Variability in daily rainfall (mm)

# Generating the 2D array of rainfall data:
months = ["June", "July", "August", "September"]
days_in_month = 30
rainfall_data = np.zeros((4, days_in_month))

for i in range(4):
    # Simulate daily rainfall using a normal distribution:
    rainfall_data[i, :] = np.clip(np.random.normal(mean_rainfall[i],
                                  std_deviation[i], days_in_month), 0, None)
# Round to 2 decimal digits:
rainfall_data = np.round(rainfall_data, 2)

In [ ]:
print(rainfall_data)