In [6]:
import numpy as np

# Linear Algebra with NumPy

In the previous notebooks we explored NumPy arrays and their basic operations.
Here we'll focus on the basic NumPy commands for doing Linear Algebra, which is
perhaps even more important than Calculus for many engineering applications,
such as structural analysis, signal processing, optimization and circuit
analysis, among others. It is also essential for machine learning and computer graphics.

## $ \S 1 $ Basic operations on vectors

### $ 1.1 $ Vector addition and scalar multiplication

We saw in the previous notebook that a vector such as $ (1, 2, 3) $
can be represented in NumPy as a $ 1D $ array:

In [ ]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

We can also use NumPy to perform all of the familiar operations on vectors.

Given vectors $ \mathbf v = (v_1, v_2, \cdots, v_n) $ and $ \mathbf w = (w_1,
w_2, \cdots, w_n) $ with the same number of coordinates, their __sum__ and
__difference__ are computed element-wise:
$$
\begin{alignat*}{2}
\mathbf{v} + \mathbf{w} &= (v_1 + w_1, v_2 + w_2, \ldots, v_n + w_n) \\
\mathbf{v} - \mathbf{w} &= (v_1 - w_1, v_2 - w_2, \ldots, v_n - w_n)
\end{alignat*}
$$
NumPy uses the same notation:

In [ ]:
s = v + w
print(s, type(s))

d = v - w
print(d, type(d))

__Scalar multiplication__ of a vector by a factor $ c \in \mathbb{R} $ is also defined
element-wise:
$$
c\, \mathbf v = (c\,v_1, c\,v_2, \cdots, c\,v_n)\,.
$$

In [ ]:
print(2 * v)
print(-3.14 * v)
print(0 * v)

Naturally, we may also write $ -\mathbf v $ instead of $ (-1)\mathbf v $. Try it in the code cell below:

If we operate on an array whose datatype is `int` and any floating-number is
involved in the operation, then the result will be of datatype `float`.  A similar
observation applies to any other type coercion.

In [ ]:
# `v.dtype` yields the datatype of the elements of v.
# We will study `dtype` in more detail later.
v = np.array([1, 2, 3])
print(v, v.dtype)

u = 1.0 * v
print(u, u.dtype)

__Exercise:__ Can you explain the output of the following cell?

In [ ]:
x = np.array([-1, 0, 1, 3])
b = np.array([True, False, True, False])

x_plus_b = x + b
print(x_plus_b, x_plus_b.dtype)

### $ 1.2 $ Dot products

The __dot product__ $ \mathbf v \cdot \mathbf w $ of two vectors $ \mathbf v =
(w_1, w_2, \cdots, w_n) $ and $ \mathbf w  = (w_1, w_2, \cdots, w_n) $ of the
same shape is the sum of the products of their corresponding coordinates:
$$
\boxed{\ \mathbf v \cdot \mathbf w = \sum_{i=1}^n v_i\,w_i =  v_1w_1 + v_2w_2 + \cdots + v_nw_n\ } 
$$
The `dot` function computes dot products:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 0, -1])

dot_product = np.dot(a, b)
print(dot_product)

Equivalently, we can also use the `@` operator:

In [ ]:
alternative_dot_product = a @ b
print(alternative_dot_product)

__Exercise:__ Compute the dot product of $ \mathbf{v} = (2, 3, -1) $ and
$ \mathbf{w} = (4, 0, 5) $ using `dot` and `@`.

It is easy to verify directly from the definition that the dot product is both:
* symmetric, i.e.,
    $$ \mathbf v \cdot \mathbf w = \mathbf w \cdot \mathbf v $$
* bilinear, meaning that 
\begin{alignat*}{9}
    (a\, \mathbf u + b\,\mathbf v) \cdot \mathbf w
    &= a\, (\mathbf u \cdot \mathbf w) + b\, (\mathbf v \cdot \mathbf w) \\
    \mathbf u \cdot (a\,\mathbf v + b\,\mathbf w) 
    &= a\, (\mathbf u \cdot \mathbf v) + b\, (\mathbf u \cdot \mathbf w)\,.
\end{alignat*}

Here $ \mathbf u,\,\mathbf v,\, \mathbf w \in \mathbb R^n $ and $ a,\,b \in \mathbb R\, $ are arbitrary.

### $ 1.3 $ Vector norm

The __norm__ or __length__ of a vector
$ \mathbf v = (v_1, v_2, \cdots, v_n) \in \mathbb R^n $ is defined by
$$
\boxed{\ \Vert \mathbf v \Vert = \sqrt{\mathbf v \cdot \mathbf v} = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}\ } $$
In dimension $ 2 $, this definition of "length" matches our intuitive notion and
can be justified by a simple application of Pythagoras' theorem, as illustrated
in the figure below. 

<img src="notebook_3_vector.png" alt="Vector" width="500px">

In higher dimensions we could similarly derive the formula for the length using
Pythagoras' theorem and induction. For example, the norm (length) of the vector
$ \mathbf w = (1, -2, 3) \in \mathbb R^3 $ is
$ \Vert \mathbf{w} \Vert = \sqrt{1^2 + (-2)^2 + 3^2} = \sqrt{14} $.


In NumPy, the norm of a vector can be easily computed with a call to the 
function `norm` from the `linalg` submodule:

In [ ]:
v = np.array([3, 4])

print(np.linalg.norm(v))

# Alternatively, we could take the square root of the dot product:
print(np.sqrt(v @ v))

__Exercise:__ Verify with the help of NumPy that the length of
$ \mathbf{u} = \big(\frac{1}{2}, \frac{1}{2}, \frac{1}{2}, \frac{1}{2} \big) \in \mathbb R^4 $
is $ 1 $.

⚡ We can also use `norm` to compute different norms, for instance:
$$
\begin{alignat*}{2}
    \|\mathbf{v}\|_1 &= \sum_{i=1}^n |v_i| &\quad& \text{($ L_1 $ norm for $\mathbf{v} \in \mathbb{R}^n$)} \\
    \|\mathbf{v}\|_{\infty} &= \max_{1 \leq i \leq n} |v_i| && \text{($ L_\infty$ norm for $\mathbf{v} \in \mathbb{R}^n$)}
\end{alignat*}
$$
In this notation, the usual (Euclidean) norm is also called the $ L_2 $ norm.

__Exercise:__ Let
$ \mathbf{u} = \big(\frac{1}{2}, \frac{1}{2}, \frac{1}{2}, \frac{1}{2} \big) \in \mathbb R^4 $.
Compute its $ L_1 $ and $ L_\infty $ norms by providing the additional arguments
`ord=1` and `ord=np.inf` to the `norm` function.

In [ ]:
norm_u_1 = # ...    # L_1 norm (Manhattan distance)
norm_u_inf = # ...    # L_infinity norm (maximum absolute value)

print(f"L_1 norm of u = {norm_u_1}")
print(f"L_infinity norm of u = {norm_u_inf}")

### $ 1.4 $ The geometry of dot products

Recall that two vectors are __orthogonal__ (or __perpendicular__) if and only if
their dot product vanishes. 

__Exercise:__ Determine whether the two vectors below are orthogonal by
computing their dot product:

In [ ]:
a = np.array([-3, 4, 7, 3, -6])
b = np.array([2, 5, -2, 4, 2])

More generally, recall from Linear Algebra the following relationship between the dot product and
the smallest angle $ \theta \in [0, \pi] $ between two nonzero vectors:
$$
\boxed{\ \cos \theta = \frac{\mathbf v \cdot \mathbf w}{\Vert \mathbf v \Vert \,\Vert \mathbf w \Vert}\ }
$$
                                                                                                    

__Exercise:__ Compute the angle between the vectors $ \mathbf v = (2, 0) $ and
$ \mathbf w = (3, 3) $ in degrees. Check your answer against the figure below.
_Hint:_ Use `np.arccos` to compute the arccosine and `np.degrees` to transform
the result to degrees.


<img src="notebook_3_vectors_and_angle.png" alt="Angle" width="500px">

__Exercise:__ Consider the vectors $ \mathbf a $ and $ \mathbf b $ in the 
figure below. Project $ \mathbf b $ orthogonally onto the line spanned
by $ \mathbf a $. That is, compute the projection
$$ \boxed{\ \mathbf p = \frac{\mathbf b \cdot \mathbf a}{\Vert \mathbf{a} \Vert^2}\, \mathbf a
= \frac{\mathbf b \cdot \mathbf a}{\mathbf a \cdot \mathbf a}\, \mathbf a\ } $$

<img src="notebook_3_projection.png" alt="Projection" width="400px">

In [ ]:
# a = ...
# b = ...
# p = ...
print(p)

A __unit vector__ is a vector of length $ 1 $. To get a unit vector $ \mathbf u $ having the same
direction as a given nonzero vector $ \mathbf v $, we can simply divide the latter by its norm:
$$
    \mathbf u = \frac{\mathbf v}{\Vert \mathbf v \Vert}\,.
$$
Indeed, using the properties of the dot product and the definition of the norm, we can check directly that
$$
    \mathbf u \cdot \mathbf u = \bigg(\frac{\mathbf v}{\Vert \mathbf v \Vert}\bigg) \cdot \bigg(\frac{\mathbf v}{\Vert \mathbf v \Vert}\bigg)
    = \frac{{\mathbf v \cdot \mathbf v}}{\Vert \mathbf v \Vert^2} = 1\,.
$$

__Exercise:__ How many _unit_ vectors in $ \mathbb{R}^3 $ are parallel to $ \mathbf v = (3, -4, 12) $ (i.e., lie on the same line through the origin as $ \mathbf v $)? Compute all of them using NumPy.

In [ ]:
v = np.array([3, -4, 12])

__Exercise:__ The __canonical basis__ in $ \mathbb R^3 $ consists of the three vectors
$$ \mathbf e_1 = (1, 0, 0)\,, \quad \mathbf e_2 = (0, 1, 0)\,, \quad \text{and} \quad \mathbf e_3 = (0, 0, 1) \,,$$
which have norm $ 1 $ and point in the same direction as the positive $ x $-, $ y $- and $ z$-axis, respectively.
Compute all possible dot products $ \mathbf e_i \cdot \mathbf e_j $.
Store the dot products in a $ 3 \times 3 $ matrix whose $ (i, j) $-th entry
equals $ \mathbf{e}_i \cdot \mathbf{e}_j $.
 _Hint:_ Store the vectors in a list and use two for loops. 

### $ 1.5 $ The cross product

The __cross product__ $ \mathbf v \times \mathbf w \in \mathbb R^3 $ of two vectors _in
three-dimensional space_ results in a vector that:
1. is orthogonal to both $ \mathbf v $ and $ \mathbf w $;
2. has length given by
$$
\boxed{\ \Vert{\mathbf v \times \mathbf w}\Vert = \Vert{\mathbf v}\Vert\,\Vert{\mathbf w}\Vert\,\sin \theta\ }
$$
where again $ \theta \in [0, \pi] $ denotes the smallest angle between
$ \mathbf v $ and $ \mathbf w $. Note that the expression on the right
coincides with the area of the parallelogram spanned by $ \mathbf{v} $ and $
\mathbf{w} $.

The cross product is uniquely determined by these two properties together with
the fact that:

3. the basis $ \big(\mathbf v,\, \mathbf w,\, \mathbf v \times \mathbf w \big) $ is _positively oriented_ (i.e., this
trio of vectors, in this order, satisfies the "right-hand rule").


<img src="notebook_3_cross_product.png" alt="Projection" width="500px">

Like the dot product, the cross product $ \times $ is also bilinear, but it is
antisymmetric instead of symmetric:
$$ \mathbf w \times \mathbf v = -\mathbf v \times \mathbf w \quad (\mathbf v,\, \mathbf w \in \mathbb R^3)\,.
$$
Cross products can be computed in NumPy with the function `cross`.

__Exercise:__ Let $ \mathbf{a} = (2, 1, 0) $ and $ \mathbf{b} = (1, 2, 0) $. Use
`cross` to verify that:

(a) $ \mathbf{a} \times \mathbf{b} = (0, 0, 3) $.

(b) $ \mathbf{b} \times \mathbf{a} = - \mathbf{a} \times \mathbf{b} $.

## $ \S 2 $ Basic operations involving matrices

### $ 2.1 $ Addition, subtraction and scalar multiplication

Recall that matrices are represented in NumPy as $ 2D $ arrays. Just as for
vectors, we can __add__ and __subtract__ two matrices, or more generally any two
arrays having the same shape, using `+` and `-` respectively.
Matrix addition and subtraction are performed element-wise: if $ A = (a_{ij}) $
and $ B = (b_{ij}) $, then
$$
\begin{align*}
A + B &= (a_{ij} + b_{ij}) \\
A - B &= (a_{ij} - b_{ij})
\end{align*}
$$

__Exercise:__ Compute the sum and difference of the matrices $ A $ and $ B $
given below:

In [ ]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])

B = np.array([[4, 4, 4],
              [5, 5, 5]])

# S = ... (sum)
# D = ... (difference)

print("Matrix A:\n", A, '\n')
print("Matrix B:\n", B, '\n')
print("Sum:\n", S, '\n')
print("Difference:\n", D, '\n')

Similarly, to __scale__ every element of a matrix (or, more generally, $ n
$-dimensional array) $ A $ by a scalar $ c $, we may use either `c * A` or `A * c`.

__Exercise:__  Compute $ 2M $ in by multiplying $ M $ by $ 2 $ both on the right
and on the left, where:

In [ ]:
M = np.array([
    [4, 7, 2],
    [9, 1, 5]
])
c = 2

# print("cM:\n", ... )
# print("Mc:\n", ... )

### $ 2.2 $ Matrix multiplication


__Matrix multiplication__ is the most fundamental operation in linear algebra.
Given matrices $ A $ of shape $ (m, n) $ and $ B $ of shape $ (n, p) $, their
product $ C = A B $ is a matrix of shape $ (m, p) $. The $ (i, j) $-th entry of
$ C $, denoted $ C_{ij} $, is the dot product of the $ i $-th row of $ A $ and the
$ j $-th column of $ B $:
$$
\boxed{\ C_{ij} = (\textbf{$ \mathbf{i} $-th row of $ \mathbf{A} $}) \cdot (\textbf{$ \mathbf{j} $-th column of $ \mathbf{B} $})
= \sum_{k=1}^{n} A_{ik} B_{kj}\ }
$$
In particular, for the product of two matrices to make sense, the number of
columns in the first matrix must match the number of rows in the second matrix.
Matrix multiplication should not be confused with element-wise multiplication,
which is less frequently needed in Linear Algebra.

In NumPy, matrix multiplication can be performed using the `matmul` or
`dot` functions, or the `@` operator. 

__Exercise:__ Compute the product $ AB $ of the matrices $ A $ and $ B $
below in these three ways, and compare the results.

In [ ]:
# Creating a 2 x 3 matrix A:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Creating a 3 x 4 matrix B:
B = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14],
              [15, 16, 17, 18]])

# P_1 =      (using np.matmul())
# P_2 =      (using np.dot())
# P_3 =      (using the @ operator)

print(P_1, '\n')
print(P_2, '\n')
print(P_3, '\n')
print(P_1.shape)

📝 For matrix multiplication, `dot`, `matmul` and `@` are completely equivalent
in their output and performance. The choice between them is a matter of
preference and code readability.

When multiplying a $ 2D $ array (matrix) by a $ 1D $ array (vector), the vector
is temporarily viewed as a column matrix and the operation is treated as a
matrix multiplication. Thus, matrix-vector multiplication can also be handled
by `@`, `dot` or `matmul`.

__Exercise:__ Compute the product $ A \mathbf{v} $ for $ A $ and $ \mathbf{v} $
as given below in these three ways. Determine the shape of the result;
is it a $ 1D $ array or a $ 2D $ array with only one column?

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([-1, 0, 1])


⚠️ It is a common mistake for programmers to use the `*` operator when
matrix multiplication is intended. However, `A * B` gives the
_element-wise product of $ A $ and $ B $._

__Exercise:__ Compute `C @ C`, `C * C`, `C**2` and `C**(-1)` for the matrix $ C $ below. Can you explain these results?

In [ ]:
C = np.array([[1.0, 1.0, 1.0],
              [2.0, 2.0, 2.0],
              [-3., -3., -3.]])

⚠️ Matrix multiplication is not commutative: $ A B \neq B A $ in general.

__Exercise:__ Let 
$$
    P = \begin{bmatrix} 2 & 0 \\ -1 & 3 \end{bmatrix} \quad \text{and} \quad 
    Q = \begin{bmatrix} 1 & 4 \\ 2 & -3 \end{bmatrix}
$$
Check whether $ P Q = Q P $.

__Exercise:__ For real numbers $ a,\, b $, if $ a $ and $ b $ are both nonzero,
then so is their product $ ab $. Is this also true of matrices? _Hint:_ Try to
find a nonzero $ 2 \times 2 $ matrix $ A $ such that $ A^2 $ is the null $ 2
\times 2 $ matrix.

To compute the $ n $-th power of a matrix $ A $, we can use `np.linalg.matrix_power(A, n)`.
As an application, consider the directed graph below:

<img src="notebook_3_graph.png" alt="Directed graph" width="300px">

The __adjacency matrix__  $ A $ for this graph is a $ 4 \times 4 $ matrix 
whose $ (i, j) $-th entry equals $ 1 $ if there's an edge from vertex $ i $ to
vertex $ j $ and $ 0 $ otherwise. (We start counting $ i $ and $ j $ from $ 0 $
to be consistent with our code.) Thus, in our case:
$$
A = \begin{bmatrix}
0 & 1 & 1 & 0 \\
0 & 0 & 1 & 0 \\
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 0
\end{bmatrix}
$$

The powers of an adjacency matrix have a beautiful interpretation in graph theory:
* $ A^1 = A $, the adjacency matrix itself, shows direct connections between nodes;
* $ A^2 $ shows the number of paths of length $ 2 $ between nodes;
* $ A^3 $ shows the number of paths of length $ 3 $ between nodes; and so on...
* In general, $ A^n_{ij} $ represents the number of distinct paths of length $ n $
  from vertex $ i $ to vertex $ j $ in the graph.

In the case of our graph,
$$
A^2 = \begin{bmatrix}
0 & 0 & 1 & 1 \\
1 & 0 & 0 & 1 \\
0 & 2 & 1 & 0 \\
0 & 0 & 1 & 0
\end{bmatrix}
$$
For example, the fact that $ A^2_{2,1} = 2 $ indicates that there are exactly
two distinct paths of length $ 2 $ from vertex $ 2 $ to vertex $ 1 $. Indeed, we
can check directly by looking at the graph that these paths are:
$$
2 \rightarrow 0 \rightarrow 1 \qquad \text{and} \qquad 2 \rightarrow 3 \rightarrow 1\,.
$$

__Exercise:__ Using `np.linalg.matrix_power(A, n)`:

(a) Determine the number of paths of length $ 20 $ starting at vertex $ 3 $ and
ending at vertex $ 0 $ in the graph depicted above.

(b) Determine the number of paths of length $ \le 20 $ starting at vertex $ 1 $
    and returning to that same vertex. _Hint:_ Use a for loop to add the relevant
    entries in $ I + A + A^2 + \cdots + A^{20} $.

In [ ]:
A = np.array([
    [0, 1, 1, 0],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [0, 1, 0, 0]
])

### $ 2.3 $ Identity and diagonal matrices

To instantiate a copy of the identity matrix of shape $ n \times n $,
we can use the function `identity` as follows:

In [ ]:
n = 4
I = np.identity(n)  # Create an n x n identity matrix
print(I)
print(I.dtype)

A more flexible version of `identity` allowing the creation of non-square
matrices is `eye` (the name comes from the letter 'I'):

In [ ]:
I = np.eye(3, 4)
print(I)

The third (optional) parameter of `eye` specifies an offset to the diagonal:

In [ ]:
I = np.eye(4, 4, 0)   # An offset of 0 corresponds to the main diagonal
U = np.eye(4, 4, 1)   # An offset of 1 corresponds to the diagonal immediately above the main one
L = np.eye(4, 4, -2)  # A negative offset to refers to a lower diagonal

print(I, '\n')
print(U, '\n')
print(L, '\n')

__Exercise:__ Compute the linear combination $ M^2 - 3 M + 2I $, for $ M $ the matrix below:

In [ ]:
M = np.array([[ 0, -2],
              [ 1,  3]])

The function `diag` is dual-purpose: it both creates diagonal matrices and
extracts diagonals from existing matrices, depending on its input.

In [ ]:
# np.diag creates a diagonal matrix when given a 1D array:
diagonal_values = [1, 2, 3, 4]
diag_matrix = np.diag(diagonal_values)
print(diag_matrix)

In [ ]:
# np.diag extracts the diagonal when given a 2D array:
existing_matrix = np.array([[1, 2, 3], 
                            [4, 5, 6], 
                            [7, 8, 9]])
diagonal = np.diag(existing_matrix)
print(diagonal, diagonal.shape)

__Exercise:__ Extract the diagonal elements of the matrix $ C $ below into a vector and
then compute its length and the angle it makes with the vector $ (7, -2, 1) $:

In [ ]:
C = np.array([[0, -4, 2],
              [3, 1, -5],
              [-3, 0, 2]])

### $ 2.5 $ Transposition

The transpose of a matrix $ A $ is a new matrix $ A^T $ whose rows are the
columns of $ A $ and vice versa. Formally, if $ A $ is an $ m \times n $ matrix,
then $ A^T $ is an $ n \times m $ matrix with elements $ (A^T)_{ij} = A_{ji} $.
In NumPy, the transpose of $ A $ is denoted by `A.T`:

In [5]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("A:")
print(A, "\n")
print("A^T:")
print(A.T)

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

A^T:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


__Exercise:__ A square $ n \times n $ matrix $ A $ is
__orthogonal__ if and only if its $ n $ column vectors
$ \mathbf v_1, \cdots, \mathbf v_n $ form an _orthonormal basis_ of $ \mathbb R^n $ that is,
$$
\mathbf v_i \cdot \mathbf v_j = 
\begin{cases}
1 & \text{if $ i = j $} \\
0 & \text{otherwise}
\end{cases}
\qquad \text{for each $ i,\,j = 1, \cdots, n\,. $}
$$

(a) Write a procedure `is_orthogonal` that determines whether a
given $ n \times n $ square matrix $ A $ is orthogonal. 
_Hint:_ Use the slice `A[:, i]` to extract the $ i $-th column vector of $ A $
and compute all possible dot products.

(b) Can you see any potential problems with your approach when $ A $
consists of floating-point numbers?

__Exercise:__ An equivalent condition for the orthogonality of $ A $ is that it satisfy
$$
A^TA = I_n = AA^T\,,
$$
where $ A^T $ is the transpose of $ A $ and $ I_n $ is the $ n \times n $ identity matrix.
(Actually, any one of these equations by itself already suffices for orthogonality.)
 
Write another version of `is_orthogonal` that makes use of this criterion and of
the transpose `A.T`.  When comparing to the identity, you may want to use
`np.round(B, 10)` to round all entries of $ B $ to ten decimal digits to avoid
false negatives.

### $ 2.6 $ The trace, determinant and inverse of a square matrix

Recall that the __trace__ of a square matrix is by definition the sum of all of
its diagonal entries. To compute the __trace__, __determinant__ and the
__inverse__ of a _square_ matrix, we can use the `np.trace`, `np.linalg.det` and
the `np.linalg.inv` functions, respectively. 

__Exercise:__ Compute the trace, determinant and inverse $ X^{-1} $ of $ X $.
Verify whether $ X^{-1} X = I_2 = XX^{-1} $ and explain the results.

In [ ]:
X = np.array([[3, 1, 2],
              [1, 5, 1],
              [2, 1, 4]])

# trace = ...
# determinant = ...
# inverse = ...
print(f"Trace of X: {trace:.4f}")
print(f"Determinant of X: {determinant:.2f}")
print(f"Inverse of X\n: {inverse}")

__Exercise:__ Find the area of the parallelogram spanned by the vectors 
$ (3, 5) $ and $ (2, 4) $ in $ \mathbb{R}^2 $.  Recall that this area can be
computed as the absolute value of the determinant of the matrix formed by these
vectors. _Hint:_ The absolute value function in NumPy is denoted by `np.abs`.

__Exercise:__ Given two square matrices $ C $ and $ D $ of the same size, recall
that the determinant of their product is the product of their determinants:
$$
\boxed{\ \det(CD) = \det(C) \cdot \det(D)\ }
$$
Verify this identity in the particular example where
$$
C = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix} \quad \text{and} \quad
D = \begin{bmatrix}
2 & 3 \\
1 & 4 \\
\end{bmatrix}\,.
$$
Does $ CD = DC $?

__Exercise:__ Solve the linear system of equations given by
$ A\mathbf{x} = \mathbf{b} $, where
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0 \\
\end{bmatrix} \quad \text{and} \quad \mathbf b = \begin{bmatrix}
3 \\
7 \\
8 \\
\end{bmatrix}\,.
$$
Verify your answer by multiplying $ A $ by $ \mathbf x $.
_Hint:_ Use the inverse of $ A $ to find $ \mathbf{x} = A^{-1}\mathbf{b} $.

⚡ __Exercise:__ For a list of values $ x_0, x_1, \ldots, x_n $, the corresponding __Vandermonde
matrix__ is defined as:
$$
V = \begin{bmatrix} 
1 & x_0 & x_0^2 & \cdots & x_0^{n} \\ 
1 & x_1 & x_1^2 & \cdots & x_1^{n} \\ 
\vdots & \vdots & \vdots & \ddots & \vdots \\ 
1 & x_n & x_n^2 & \cdots & x_n^{n}
\end{bmatrix}\,.
$$
This matrix arises naturally in problems involving polynomial interpolation and
differential equations. The determinant of $ V $ has a beautiful closed-form
expression:
$$
    \det(V) = \prod_{0 \leq i < j \leq n} (x_j - x_i)\,.
$$\,.
This is the product of all possible differences between 
two values, with the first one having the larger index.

(a) Write a procedure that creates a Vandermonde matrix for a given list of
input values. _Hint:_ Start with a null matrix of the appropriate dimensions and
fill the elements in one by one. Use a double for loop and the formula $ V_{ij}
= x_i^j $.

(b) Write a procedure which uses the closed formula above to compute the
determinant of the Vandermonde matrix corresponding to a list of values.
_Hint:_ Start with the value $ 1 $ for the determinant and use a double for loop
to include one factor $ (x_j - x_i) $ at a time.

(c) Test your functions on the matrix below. _Hint:_ Use `det` to check the
determinant that your procedure from item (a) yields.
$$
V = V(2, 3, 5, 7, 11) = \begin{bmatrix} 
1 & 2 & 4 & 8 & 16 \\ 
1 & 3 & 9 & 27 & 81 \\ 
1 & 5 & 25 & 125 & 625 \\ 
1 & 7 & 49 & 343 & 2401 \\ 
1 & 11 & 121 & 1331 & 14641
\end{bmatrix}
$$