In [1]:
import numpy as np

# Array attributes and methods

In this notebook we will study the fundamental _attributes_ (properties) and
_methods_ (transformations) of NumPy arrays. This will allow us to 
to analyze, manipulate and restructure our data in various ways.

## $ \S 1 $ Attributes of arrays

### $ 1.1 $ Shape and number of dimensions

The __number of dimensions__, also known as the __rank__, of an array is stored
in its `ndim` attribute. For example, the following matrix has rank $ 2 $, because
it has two __axes__, one corresponding to its rows and the other one to its columns:

<img src="array.svg" width="500" alt="Example of an array A">

In [11]:
A = np.array([[1, 2,  3,  4],
              [1, 4,  9, 16],
              [1, 8, 27, 64]])
print(A, '\n')

print(f"Number of dimensions (rank) of A: {A.ndim}")

[[ 1  2  3  4]
 [ 1  4  9 16]
 [ 1  8 27 64]] 

Number of dimensions (rank) of A: 2


⚠️ Note that the notions of (matrix) _rank_ and _number of dimensions_ (of a
vector space) studied in Linear Algebra are at odds with those in NumPy. For
instance, the `ndim` of the vector $ \mathbf{v} = (1, 2, 3) $ is $ 1 $ since
it has a single axis, despite the fact that it has three coordinates.

Perhaps the most important property of an array is its **shape**, which is the
element count along each of its axes.  Referring to the preceding example, the
shape of our matrix $ A $ is $ (3, 4) $, since it has three
rows and four columns:

In [5]:
print(A.shape)

(3, 4)


📝 The number of dimensions of an array is a positive integer, while its shape is always a tuple, even when the array is one-dimensional:

In [ ]:
primes = np.array([19, 199, 1999])
print(primes.shape)

print("Note that the shape is not '3', but rather the tuple '(3, )'")
print(type(primes.shape))

(3,)
Note that the shape is not '3', but rather the tuple '(3, )'
<class 'tuple'>


The __size__ of an array is simply the total number of elements in it:

In [ ]:
print(primes.size)

3


__Exercise:__ 

(a) What is the size of the matrix $ A $ of shape $ (3, 4) $ that we considered
above?

(b) What are the rank (i.e., number of dimensions), shape and size of an empty
$ 1D $ array? An empty $ 2D $ array?

__Exercise:__ If an array has shape $ (2, 3, 4) $, what is its size? More generally, what is the size of an array of shape $ (n_1, n_2, \cdots, n_d) $? _Hint:_ We have $ n_1 $ options for the first index, for each of these we have $ n_2 $ options for the second index, for each of these we have $ n_3 $ options for the third index, etc., hence in total we have $ \underline{\hspace{1cm}} $ elements.

__Exercise:__ A _square matrix_ has the same number of rows and columns.

(a) Write a function `is_square(A)` that takes a $ 2D $ array as its
argument and returns `True` or `False` depending on whether the given matrix is
square or not.  _Hint:_ Use the shape to decide this.

(b)  What is a reasonable definition of a "cubic" $ 3D $ array and how could we
check that?

(c) How would you generalize to multidimensional arrays? _Hint:_ To verify whether
an array of shape $ (n_1, n_2, \cdots, n_d) $ is "hypercubic" (all of its axes have
the same length), we can check whether
$$
\texttt{A.shape} = (n_1, n_2, \cdots, n_d) == (n_2, n_3, , \cdots, n_d, n_1) = \texttt{A.shape[1:] + (A.shape[0], )}
$$

### $ 1.2 $ Attributes and related terminology

An instance, or __object__, of a specific class, such as the array $ A $ of type
`ndarray`, is equipped with a set of predefined **attributes**. Attributes are 
_properties inherent to every instance of the class_.
The **state** of an object is _the set of current values of all of
its attributes._

📝 To access an attribute `a` of an object `x`, the syntax is always `x.a`.

For example, suppose that we want to design a Python class `Car` to represent cars.
An instance of this class would then correspond to one specific car
in the real world.  Some plausible attributes of this class could be:
* Its color (say, `color`, of type `str`).
* The year in which it was manufactured (say, `year`, of type `int`).
* Whether it is electric or not (say, `electric`, of type `boolean`).
* The fuel efficiency of the car (say, `kilometers_per_liter`, of type `float`).

And so on for any other relevant property of cars that we might want to include
in our model. To access, say, the color of an instance `my_car` of the class
`Car` we would type `my_car.color`.

Note that the values of these attributes for different car instances will vary,
in general. However, from this example we can easily imagine a situation where
two cars have exactly the same state, as defined by their set of attribute
values, and yet they are distinct objects, i.e., they have different
_identities_, meaning that they reside in different memory locations and are
hence independent.

### $ 1.3 $ The main attributes of arrays

Although arrays come with several attributes, most of them relate to the array's
internal representation or low-level utilities, such as the number of bytes
consumed by the elements of the array. The five most frequently used and
conceptually important are:

| Attribute   | Description                                    | Type      |
|-------------|------------------------------------------------|-----------|
| `ndim`      | Number of dimensions (rank) of the array  | `int`   |
| `shape`     | Number of elements that lie along each axis | `tuple`     |
| `size`      | Total number of elements in the array     | `int`   |
| `dtype`     | Data type of the _elements_ of the array    | `dtype`  |
| `T`         | Transpose of the array                    | `ndarray`    |


__Exercise:__ For the following arrays $ B $ and $ \mathbf v $:

(a) Check their attributes. Is the datatype of $ \mathbf v $ what you expected?

(b) Verify that the type of each attribute matches the one described in the last
column of the table using the Python built-in function `type`.

In [ ]:
B = np.array([[True, False, True],
              [False, True, False]])

In [ ]:
v = np.array([1, 2, 3.])

### $ 1.4 $ The datatype of an array

NumPy arrays are designed to store elements of a single datatype, and _these
datatypes are specific to NumPy_. Many of these are based on C's native types;
this ensures high performance and a lighter memory footprint. As an example, the
datatype of the matrix $ A $ above is `int64`, which represents integers using $
64 $ bits. In contrast, the built-in Python type `int` can hold arbitrarily
large integers.

It is also possible to work
with arrays of arbitrary Python objects by using the datatype `object`. Because
in this case what is stored in the array is only a reference to each object (not
the object itself), the entries don't even need to have the same Python type:

In [4]:
import numpy as np
complex_array = np.array(["pandas",  [1, 2, 3], 1 + 1j], dtype=object)

for item in complex_array:
    print(f"Item: {item}\t of type: {type(item)}")

Item: pandas	 of type: <class 'str'>
Item: [1, 2, 3]	 of type: <class 'list'>
Item: (1+1j)	 of type: <class 'complex'>


To create a NumPy array with a specified datatype, we can use the `dtype`
parameter in any array creation function. For example:

In [10]:
v = np.array([1, 2, 3, 4], dtype="float32")
print(f"Datatype of v: {v.dtype}")
print(v)

Datatype of v: float32
[1. 2. 3. 4.]


Note that in this form the datatype is passed as a string argument.

__Exercise:__

(a) Create a $ 2D $ array $ B $ of shape $ (2, 3) $ whose elements are all
    `True`. _Hint:_ Invoke the `ones` function 
    with the appropriate shape and `dtype="bool"` as one of the arguments.

(b) Instantiate $ \mathbf b = (2, 3, 4, 5) $ of type `uint32` (unsigned, $ 32
$-bit integer) using `linspace`.

(c) Construct a $ 2D $ array $ C $ of shape $ (4, 2) $ in which all entries are
equal to $ 1 + i $, of type `complex`. _Hint:_ Use `full` and recall that
the imaginary unit in Python is denoted with `j`.

### $ 1.5 $ The transpose

For $ 2D $ arrays, the __transpose__ is obtained by swapping rows and columns.
The transpose of a matrix is very important in Linear Algebra and its
applications to statistics and machine learning.  The `T` attribute in NumPy
arrays provides a __view__ of the transposed array, meaning that `A.T` shares
the same underlying data buffer as the original array `A`. In particular, any
modification to one of them affects the other.

__Exercise:__ 

(a) What is the transpose of a $ 1D $ array?

(b) What is the transpose of a $ 3D $ array, i.e., how is it obtained from the original array?
    Make a conjecture and then try it out on an array of shape $ (2, 3, 4) $.

(c) More generally, what do you think would be the most reasonable definition of the transpose of an $ n $-dimensional array?
    _Hint:_ Create an array of shape $ (2, 3, 4, 5) $ and inspect the shape of its transpose.

### $ 1.6 $ Comparing two arrays for equality

<div style="
    background-color: #fff3cd; 
    border: 1px solid #ffeeba; 
    border-left: 5px solid #ffc107; 
    border-radius: 4px; 
    color: #856404; 
    margin: 10px 0px; 
    padding: 15px;">
    <span style="font-size: 24px; margin-right: 10px; vertical-align: middle;">⚠️</span>
    Contrary to what might be expected, when applied to two arrays of the same
    shape, the <code>==</code> operator performs an element-wise comparison and
    returns a Boolean <i>array</i> having the same shape as the operands. In contrast,
    <code>np.array_equal(A, B)</code> also performs a full array comparison, but returns
    a <i>single</i> Boolean value depending on whether the arrays have the same shape
    and all corresponding elements are equal.
</div>

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

print(a == b)  # Element-wise comparison, result is an array
print(np.array_equal(a, b))  # Overall array equality, result is True or False

[ True  True  True]
True


__Exercise:__ Write a Python function which prints a message indicating whether
a given matrix $ A $ is _symmetric_ (i.e., whether $ A^T = A $),
_anti-symmetric_ ($ A^T = -A $) or neither.
Does your function work correctly when $ A $ is not square?

In [ ]:
def is_symmetric(A):
    # complete...

__Exercise:__ A square matrix $ A $ is called _orthogonal_ if it satisfies
$$
A^TA = I_n = AA^T\,,
$$
where $ A^T $ is the transpose of $ A $ and $ I_n $ is the $ n \times n $ identity matrix.
(Actually, any one of these equations by itself already suffices for orthogonality.)
Write a procedure `is_orthogonal(A)` that makes use of this criterion to decide
whether $ A $ is orthogonal.  When comparing to the identity, you may want to
use `np.round(B, 10)` to round all entries of $ B $ to ten decimal digits to
avoid false negatives.

## $ \S 2 $ Reduction and accumulation methods

### $ 2.1 $ Methods and related terminology

While attributes describe the properties of an object, **methods** define what
an object can do: they are functions that are bound to the object and that can
access or modify its state. Methods encapsulate behavior that is appropriate for
the class of objects they belong to, just as attributes encapsulate state.

📝 To invoke a method `m` on an object `x`, the syntax is `x.m(<arguments>)`.

Continuing the example from $ \S 1.2 $, we could think about implementing
the following methods for our class representing cars:
* Starting the engine (say, `start_engine()`, which returns nothing but changes the car's state).
* Checking if maintenance is needed (say, `needs_maintenance()`, which returns a `boolean`).
* Refueling the car with a certain amount of gas (say, `refuel(amount)`, which returns the new fuel level as a `float`).

For example, to refuel an instance `my_car` of the `Car` class, we could issue
the instruction `my_car.refuel(20)`.

In the context of NumPy arrays, methods like `sum()` perform calculations on the
array's data and return results, while methods like `sort()` modify the array in
place, without returning anything.

In [5]:
v = np.array([2, 3, 1])

print(f"v = {v}")
print(f"Sum of the values in v: {v.sum()}")

v.sort()
print(f"v after sorting: {v}")

v = [2 3 1]
Sum of the values in v: 6
v after sorting: [1 2 3]


### $ 2.2 $ Main reduction and accumulation methods

NumPy arrays have several __reduction methods__ that transform data
into simpler forms.  For example, the `min` and `max` methods yield the minimum
and maximum elements of an array. Similarly, `argmin` and `argmax` return the
_index_ of the minimum and maximum elements. Here's an illustration in the
case of a $ 1D $ array `a`:

<img src="max_min.svg" width="1400" height="300" alt="Max and min methods">

📝 When the minimum value occurs multiple times, `argmin` returns the index of
the first occurrence. When called on a multidimensional array, it returns
the index of the minimum element of the _flattened_ ($ 1D $) version of the array:

In [14]:
arr = np.array([[3, 2, 4], 
                [1, 4, 1]])
print(arr)

idx = arr.argmin()
print(f"Argmin: {idx}")
print(type(idx))

[[3 2 4]
 [1 4 1]]
Argmin: 3
<class 'numpy.int64'>


The result in this case is $ 3 $ because that's the first index of an element
having the minimum value $ 1 $ in the flattened array $ (3, 2, 4, 1, 4, 1) $.
Of course, similar comments apply to `argmax`.

__Exercise:__ Compute `min`, `max`, `argmin` and `argmax` of the following $ 2D $ array.
Explain the results of the two latter methods.

In [15]:
A = np.array([[2, 0, 3],
              [3, 1, 0],
              [1, 2, 0]])
print(A, '\n')

[[2 0 3]
 [3 1 0]
 [1 2 0]] 



The `sum` and `prod` are further reduction methods that compute the sum and product of
all the elements in an array, respectively. The `cumsum` and `cumprod` are
_accumulation_ methods. Instead of returning a single number, they produce an
array of the same shape as the original, obtained by computing the _cumulative_
sum and product of the entries in the array, respectively:

<img src="sum_prod.svg" width="1400" height="300" alt="Sum and product methods">

📝 None of the reduction and accumulation methods perform in-place
transformations. Instead, they return new arrays (or numbers) with the computed
results while leaving the original array unchanged.

__Exercise:__ Verify the results in the preceding example using NumPy and directly from
the definitions of the methods.

__Exercise:__ Create a function that calculates compound interest using
`cumprod`. Given a principal amount and an array of monthly interest rates
(as decimal values), return the account balance after each month.
Test it on the values below. _Hint:_ The growth factors are given by
$ 1 + \text{monthly rates} $. The balances will be the product of the
principal amount and the cumulative product of the growth factors.

In [6]:
principal = 1000
monthly_rates = np.array([0.01, 0.012, 0.008, 0.011, 0.009, 0.013])
# balances = ???

The reduction methods `mean`, `var` and `std` provide basic
statistical operations which are essential for data analysis, namely,
they compute the (arithmetic) mean, variance and standard deviation
of the set of elements in the array, respectively. For instance:

<img src="mean_var.svg" width="1400" height="300" alt="Statistical reduction methods">

Recall that the __variance__ of a collection of numbers $ x_i $ is the expected
value of the squared deviation from the mean; it measures how spread out the
values are.  The __standard deviation__ is simply the square root of the
variance.  In symbols, if 
$$
\mu = \frac{1}{n} \sum_{i=1}^{n} x_i
$$
denotes the mean, then
$$
\sigma^2 = \text{Var} = \frac{1}{n} \sum_{i=1}^{n} (x_i - \mu)^2 \qquad
\text{and} \qquad 
\sigma = \text{Std} = \sqrt{\text{Var}} = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (x_i - \mu)^2}
$$
As above, the standard deviation is often denoted by $ \sigma $.

__Exercise:__

(a) Verify using the definitions that the values in the preceding illustration
are correct.

(b) Compute the median of this array with the _function_ (not method)
`np.median`. Recall that the __median__ is the middle value of a dataset when it is
arranged in ascending order. If there is an even number of values, the median is
the average of the two middle values. 

__Exercise:__ What are the mean, median, variance and standard deviation of an
array whose elements all have the same value $ c $?

__Exercise:__ Given the $ 1D $ array below, calculate the mean and standard
deviation of all numbers in it that are greater than $ 50 $. _Hint:_ Use a
boolean mask to filter the values $ > 50 $.

In [7]:
rng = np.random.default_rng(0)
v = rng.integers(1, 101, size=100)
# First 20 elements:
print(v[:20], "...")

# Your solution here:
# print(f"\nMean of values greater than 50: {...:.2f}")

[86 64 52 27 31  5  8  2 18 82 65 92 51 61 98 73 64 55 56 94] ...


__Exercise:__ The _Wallis product_ is the following infinite product
$$
2\,\prod_{k=1}^{\infty} \frac{4k^2}{4k^2 - 1} = 2 \cdot
\frac{4}{3} \cdot \frac{16}{15} \cdot \frac{36}{35} \cdot \frac{64}{63}
\cdot \frac{100}{99} \cdots
$$

(a) Create a procedure `wallis_product(n)` that computes the partial products
$ (p_1, p_2, \cdots, p_n) $ as a vector ($ 1D $ array), where
$$
p_n = 2\,\prod_{k=1}^{n} \frac{4k^2}{4k^2 - 1}\,.
$$
_Hint:_ First create a vector whose $ k $-th coordinate is the term $ \frac{4k^2}{4k^2 - 1} $,
then take its `cumprod` and multiply the result by $ 2 $.

(b) Can you recognize the value (limit) of the infinite product? Make a conjecture, then
test it by computing `wallis(n)` for a large value such as $ n = 100\,000 $ and
printing a slice with step $ \frac{n}{100} $ (use `//` for integer division).

### $ 2.3 $ Applying reduction and accumulation methods along an axis

As an optional argument to any of these methods, we can designate an axis
__along which__ the operation should take place. As always in Python, indexing is
zero-based.

<img src="array_sum.svg" width="800" alt="Summing the entries of an array along an axis">

If we think of $ A $ as the matrix $ A = (a_{ij}) $, where $ i $ is the index
for axis $ 0 $ (i.e., the index of rows), then taking the sum _along_ this axis
means that, for each $ j $, NumPy computes
$$
\sum_{i} a_{ij}
$$
resulting in the preceding vector since $ A $ has four columns. To put it
another way, _the axis specified as the argument to method is the one that gets
operated over_, and hence it collapses.

__Exercise:__ Compute the products of the rows and of the columns in the array
$ C $ given below along both axes. Explain the results.

In [33]:
C = np.array([[2, 1, 3],
              [3, 2, 1]])
print(C)

[[2 1 3]
 [3 2 1]]


__Exercise:__ Understanding how the axis parameter works is crucial;
this exercise will help you master this.
Given the matrix $ A $ in the code cell below:

(a) Find the maximum value in each row (i.e., along the columns).

(b) Calculate the average of each column (i.e., along the rows).

(c) Determine the index of the maximum element in each row (i.e., along the columns).

(d) Compute the standard deviation of the values in each row.

(e) Find the cumulative sums for each row using the `cumsum` method. 

In [9]:
A = np.array([[1, 2, 3, 4],
              [3, 3, 3, 3]])
print(A)

[[1 2 3 4]
 [3 3 3 3]]


📝 It is possible to apply the methods along multiple axes by passing a tuple of
axes to the `axis` parameter. This performs the operation across the specified
dimensions simultaneously.

__Exercise:__ Apply `sum` along axes $ 1 $ and $ 2 $ of the following $ 3D $ array
and explain the result. _Hint:_ Pass the argument `axis=(1, 2)`.

In [10]:
M = np.arange(-12, 12).reshape(2, 3, 4)
print(M)

[[[-12 -11 -10  -9]
  [ -8  -7  -6  -5]
  [ -4  -3  -2  -1]]

 [[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]]


### $ 2.4 $ Other reduction and accumulation methods

Arrays have several more methods besides the ones discussed above. To get a listing
of all attributes and methods associated to an object `a` (not necessarily an
array), you can run the Python command `dir(a)`.  Also, in Jupyter notebooks,
typing `?` before or after an object or function name (e.g., `A?` or
`?np.array`) displays detailed documentation about it:

In [11]:
A.sum?

Docstring:
a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

Return the sum of the array elements over the given axis.

Refer to `numpy.sum` for full documentation.

See Also
--------
numpy.sum : equivalent function
Type:      builtin_function_or_method

Here we will mention only two additional, very useful methods: `any` and `all`, which are
Boolean reduction methods:

* `any` returns `True` if and only if at least one element in the array is true (or non-zero).
   It is equivalent to an OR operation across elements.
* `all` returns `True` if and only if every element in the array is true (or non-zero). It is
   equivalent to an AND operation across elements.

Both accept an axis argument to apply the operation along specific dimensions,
and both handle non-boolean arrays by treating any nonzero values as true.

__Exercise:__ You have sensor readings from multiple devices collected
throughout the day (provided below).  Create a function that checks if any
sensor reported a critical value (above $ 95 $) and if at all sensors
remained operational (above $ 0 $), and prints a corresponding message
otherwise indicating at which hour the problem occurred. Test your
function on the data provided below.

In [ ]:
# Each row of the data represents a time interval and each column a different sensor:
sensor_data = np.array([
    [45, 62, 78, 81, 56],  # Hour 0
    [47, 65, 76, 82, 58],  # Hour 1
    [52, 68, 81, 85, 61],  # Hour 2
    [56, 72, 85, 88, 65],  # Hour 3
    [62, 78, 92, 93, 71],  # Hour 4
    [68, 83, 96, 91, 75],  # Hour 5 - Critical value
    [65, 81, 93, 87, 72],  # Hour 6
    [60, 76, 88, 84, 69],  # Hour 7
    [54, 71, 82, 80, 63],  # Hour 8
    [51, 67, 78, 78, 59],  # Hour 9
    [48, 65, 75, 75, 57],  # Hour 10
    [46, 63, 73, 74, 54],  # Hour 11
    [42, 59, 69, 70, 51],  # Hour 12
    [39, 55, 65, 68, 48],  # Hour 13
    [36, 53, 61, 65, 45],  # Hour 14
    [32, 48, 58, 61, 41],  # Hour 15
    [29, 43, 54, 58, 37],  # Hour 16
    [25, 38, 49, 53, 33],  # Hour 17
    [22, 35, 44, 49, 29],  # Hour 18
    [18, 30, 40, 46, 25],  # Hour 19
    [15, 28, 37, 42, 21],  # Hour 20
    [13, 0, 35, 39, 18],   # Hour 21 - Sensor failure (0 value)
    [11, 25, 32, 36, 15],  # Hour 22
    [10, 22, 30, 35, 13],  # Hour 23
])

def validate_sensor_data(data, critical_threshold=95, operational_threshold=0):
    critical_readings = sensor_data > critical_threshold
    operational_sensors = sensor_data > operational_threshold
    # complete ...

__Exercise:__ Given a $ 2D $ array `data` of shape $ 100 \times 5 $ representing a
dataset where each row is an entry and each column corresponds to a different variable:

(a) Calculate the mean and standard deviation of each variable.

(b) Using `argmin`, identify the variable with the smallest variance, suggesting it has the
least spread.

In [13]:
data = rng.normal(size=(100, 5))

print(data[:5])  # Display first five rows of the table

# (a) Mean and standard deviation of each variable (column):

# (b) Find the variable with the smallest variance:

[[ 0.35738041 -1.20831863 -0.00445413  0.65647494 -1.28836146]
 [ 0.39512206  0.42986369  0.69604272 -1.18411797 -0.66170257]
 [-0.43643525 -1.16980191  1.73936788 -0.49591073  0.32896963]
 [-0.25857255  1.58347288  1.32036099  0.63335262 -2.20350988]
 [ 0.05202897  0.68368619  1.00396158 -0.61790704  1.82201136]]


## $ \S 3 $ Reshaping and transforming arrays

### $ 3.1 $ Changing the datatype and converting an array to a list

Recall that the `dtype` attribute of an array stores its datatype. We can create
a new array with a different datatype from a given array by using the method
`astype`, provided that the datatype conversion makes sense:

In [14]:
# Let's begin by creating an array of strings:
A = np.array([["1", "-2"],
              ["3", "-4"]])
print(A, '\n')

# Convert the datatype to double-precision (64 bit) floating-point numbers:
A_double = A.astype("float64")
print(A_double.dtype, '\n', A_double)

[['1' '-2']
 ['3' '-4']] 

float64 
 [[ 1. -2.]
 [ 3. -4.]]


📝 Note that the datatype is passed as a string. Actually these are just
convenient aliases for the true (NumPy) type names, such as `np.float64` and
`np.bool_`, which can also be passed directly.


__Exercise:__ What happens if you try to convert a numeric array to one whose
datatype is `bool`? What about the converse, i.e., from `bool` to, say, `int32`?

In [15]:
numbers = np.array([-2, -1, 0, 1, 2])

bool_vals = np.array([True, False, True, True])

📝 Although we have been speaking about the "conversion" from one type to another,
`astype` doesn't actually modify the original array; instead, it always creates a
_new copy_ of the original array having the prescribed datatype. This occurs
even when the target datatype is the same as the original.

__Exercise:__ Prove that the two arrays $ \mathbf{u} $ and $ \mathbf{v} $ below
are independent by modifying one of them and checking that the other one
is unaffected.

In [16]:
u = np.array([1, 2, 3])
print(f"Original u: {u} of type {u.dtype}")

v = u.astype("int64")
print(f"Original v: {v} of type {v.dtype} \n")

# Modify v and check if u is affected:

Original u: [1 2 3] of type int64
Original v: [1 2 3] of type int64 



The `tolist` method is used to convert arrays to Python lists. Given an
$ n $-dimensional array, it returns a nested list with $ n $ levels of nesting:

In [37]:
arr1d = np.array([1, 2, 3, 4])
list1d = arr1d.tolist()
print(list1d)

arr2d = np.array([[1, 2], [3, 4]])
list2d = arr2d.tolist()
print(list2d)
print(type(list2d))

[1, 2, 3, 4]
[[1, 2], [3, 4]]
<class 'list'>


Since we lose NumPy's performance benefits when we convert an array to a native
Python object, `tolist` should only be used when we specifically need to
interface with code that does not support NumPy.

### $ 3.2 $ Modifying the shape of arrays

Reshaping arrays is a common and fundamental operation in NumPy. There is both
a function and a method named `reshape` that can accomplish this:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a, end='\n\n')

A = np.reshape(a, (3, 2))  # Here we use the _function_ `reshape`

B = a.reshape((2, 3))   # Here we use the `reshape` _method_

print(A, end="\n\n")
print(B, end="\n\n")

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]



Note that when we reshape an array, the new shape must be compatible with the
size of the original array, in the sense that the size (total number of
elements) must remain the same. For example, the following results in an error:

In [ ]:
C = np.reshape(a, (2, 2))

When reshaping, we may also specify $ -1 $ in a dimension to instruct
NumPy to infer the number of elements along that dimension from the size of the
array and that of the remaining dimensions. This is especially useful when an
array is passed to us by the user as an argument in a function call, but we do
not know in advance how many entries it has:

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
A = a.reshape((-1, 1))  # Reshape into a column vector
print(A)

In this example we wanted to reshape our array so that the result would have
one column, but didn't want to figure out how many rows it should have for that
to happen. Here's another example, in which we reshape a $ 1D $ array into a
matrix and then to a row vector:

In [ ]:
x = np.arange(1, 13)
X = x.reshape((3, -1))
x_row = X.reshape((1, -1))

print(x, end='\n\n')
print(X, end='\n\n')
print(x_row, end='\n\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]



📝 There is no essential difference between the function and the method versions
of `reshape`. In both cases, NumPy returns a _new_ array, while the original
array remains unchanged. However, these operations provide a view of the
original array's data whenever possible, meaning that they do not copy the
array's _data_ unless necessary. Thus, modifications to the data in the reshaped
array can affect the original array and vice versa. Let's use the previous
example to illustrate this:

In [ ]:
X[0, 0] = -23  # Modify the top left element of X
print(x)  # The 0th element of x has also been affected!

To create an independent, deep copy of a NumPy array, we can use the `copy` method.
This method generates a new array object with the same data as the original
array, but stored in a separate memory location.

In [ ]:
y = np.arange(3)  # y is the 1D array with entries 0, 1, 2
Y = y.copy().reshape((1, -1))  # Reshape y into an independent 2D row vector
y[0] = 10  # Modify 0th element of y

print(y)
print(Y)  # The 0th element of Y is not affected, since Y is an independent copy

__Exercise:__ Given a $ 1D $ array of $ 100 $ elements, reshape it into a $ 10
\times 10 $ matrix. Then, normalize the matrix so that all values are scaled to
lie between $ 0 $ and $ 1 $ (inclusive). _Hint:_ Determine the maximum $ M $ and
minimum $ m $ of all entries, write a linear function $ f $ that takes $ [m, M] $ into $ [0, 1] $
and then apply it to the entire array.

In [ ]:
# Generate random array of 100 elements
data = rng.integers(0, 1000, size=100)
print(data)

[400 787 316 239 791 876  79  58 671 336 573 150 860 450 894 796 705 230
 767  52 570 404 996 198 946  90 623 580 898 298 902 671 890 199 758 942
  48 365 636 105 510 629 763 927 409 440 474 954 195 499  49 425 945 620
 349 995 603 948  16 460 834 757 407 497 420 529 230 785  77 414 281 734
 749 711 924 932 184 114 132 729 970 927 668 967 871  14 119 863  82 981
 827 957 360 148 516 972 367 889 383 822]


### $ 3.3 $ The `ravel` and `flatten` methods

The `flatten` method takes a multi-dimensional array and returns a new,
independent _one-dimensional_ array containing all of the elements of the original
array. 

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
a = A.flatten()  # Creates a new 1D array with a copy of data
print(a)

# Let's verify it's a copy:
a[0] = 99
print(f"\nAfter modifying a[0]:\n{A}")
print(f"a = {a}")

[1 2 3 4]

After modifying a[0]:
[[1 2]
 [3 4]]
a = [99  2  3  4]


The order in which the elements are placed in the flattened array is based on
the lexicographic ordering of their indices in the original array. For example,
if we are dealing with a $ 3D $ array, then the entry at position $ (0, 0, 2) $
comes before the entry at $ (0, 1, 0) $, which will be placed before the entry
at $ (1, 0, 0) $.

In [ ]:
A = np.arange(6).reshape((2, 3))
print(A)

a = A.flatten()
a[0] = 10

print(a)
print(A)

[[0 1 2]
 [3 4 5]]
[10  1  2  3  4  5]
[[0 1 2]
 [3 4 5]]


NumPy provides another method called `ravel` that is similar to `flatten` but
with an important difference: while `flatten` always returns a deep copy of the
data, `ravel` returns a view when possible, which makes it more
memory-efficient.

__Exercise:__ Apply `ravel` and `flatten` to the matrix $ A $ below to obtain
two vectors $ \mathbf{r} $ and $ \mathbf{f} $. Verify whether changes to
$ A $ affect either vector.

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
print(A)

[[1 2]
 [3 4]]


### $ 3.4 $ Using `resize` method and function

Unlike `reshape` which requires the total number of elements to remain the same,
`resize` can change the total size of an array. The `resize` method modifies the
array in-place, while the `np.resize` function returns a new array. If the
new size is greater than the old one then the _method_ fills the missing entries
with zeros, while the _function_ cycles through the elements of the original array:

In [ ]:
# Using resize method (modifies in-place), fills with 0 if necessary:
a = np.array([1, 2, 3, 4])
print(f"Original a: {a}")

a.resize(6)  # Resize in-place to length 6
print(f"After a.resize(6): {a}")

Original a: [1 2 3 4]
After a.resize(6): [1 2 3 4 0 0]


In [ ]:
# Using resize function (returns new array)
b = np.array([1, 2, 3, 4])
C = np.resize(b, (2, 3))

print(f"\nOriginal b: {b}")
print(f"After np.resize(b, (2, 3)):\n{C}")


Original b: [1 2 3 4]
After np.resize(b, (2, 3)):
[[1 2 3]
 [4 1 2]]


### $ 3.5 $ Combining arrays with `hstack` and `vstack`

NumPy provides several functions to stack arrays together. The most commonly used are `hstack` (horizontal stack) and `vstack` (vertical stack).

In [ ]:
# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontal stacking (side by side):
h_stacked = np.hstack((a, b))
print(f"Horizontal stack of a and b: {h_stacked}")

# Vertical stacking (one above the other):
v_stacked = np.vstack((a, b))
print(f"Vertical stack of a and b:\n{v_stacked}")

Horizontal stack of a and b: [1 2 3 4 5 6]
Vertical stack of a and b:
[[1 2 3]
 [4 5 6]]


__Exercise:__ Stack the two matrices $ A $ and $ B $ below horizontally and vertically.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

### $ 3.6 $ Finding unique elements with `np.unique`

The `np.unique` function returns the sorted unique elements of an array. It can also return counts of each unique value when the `return_counts` parameter is set to `True`.

In [ ]:
data = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
print(f"Original array: {data}")

# Get unique elements:
unique_elements = np.unique(data)
print(f"\nUnique elements: {unique_elements}")

# Get unique elements and their counts:
unique_elements, counts = np.unique(data, return_counts=True)
print(f"\nUnique elements: {unique_elements}")
print(f"Counts: {str(counts):>24}")

Original array: [3 1 4 1 5 9 2 6 5 3 5]

Unique elements: [1 2 3 4 5 6 9]

Unique elements: [1 2 3 4 5 6 9]
Counts:          [2 1 2 1 3 1 1]


__Exercise:__ Use `argmax` to find the most common element in the array `data` of the preceding example.

### $ 3.7 $ Flipping arrays with `np.flip`

The `np.flip` function reverses the order of elements in an array along a specified axis. It always
returns a new, independent array, not a view of the original.

In [ ]:
# Create a 1D array:
a = np.array([1, 2, 3, 4, 5])
print(f"Original array: {a}")
print(f"Flipped array: {np.flip(a)}")

__Exercise:__ Given the $ 2D $ array $ A $ below:

(a) Flip $ A $ along its $ 0 $-th axis using `flip` with the argument `axis=0`.

(b) Flip the columns of $ A $.

(c) Flip both axes of $ A $ by using `flip` without providing an `axis` argument.

(d) Can you accomplish the same results using slices of type `::-1`? What is the difference?
_Hint:_ What happens if you modify the flipped array, is the original one affected?

In [ ]:
# Create a 2D array
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(f"\nOriginal 2D array:\n{A}")

# (a) Flip along axis 0 (rows):

# (b) Flip along axis 1 (columns):

# (c) Flip along both axes:


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


__Exercise:__ The $ 2D $ of shape $ 28 \times 28 $ in the code cell below
represents a grayscale image. Write a function to rotate this image $ 90 $ degrees
clockwise.

_Hint_: This can be accomplished by first transposing the array and then
flipping it vertically (i.e., reversing the order of the entries along each
column) with an appropriate slice or using `flip`. This is illustrated in the
$ 3 \times 3 $ example below, but the same idea works in any dimension.
$$
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix}
\overset{\text{transpose}}{\longrightarrow}
\begin{bmatrix}
a & d & g \\
b & e & h \\
c & f & i \\
\end{bmatrix}
\overset{\text{flip ver.}}{\longrightarrow}
\begin{bmatrix}
g & d & a \\
h & e & b \\
i & f & c \\
\end{bmatrix}
$$

In [ ]:
image = np.array(rng.integers(0, 256, size=(28, 28)))
print(image[:5, :5])

def rotate_90_clockwise(img):
    """ Rotate a 2D array 90 degrees clockwise.  """

[[209 215 215 107 109]
 [139 143 115 203  34]
 [180 127  65  62 170]
 [  5 237  66 204  48]
 [206 217  69 153  58]]


### $ 3.8 $ The `squeeze` method

The `squeeze` method removes single-dimensional entries (axes with length $ 1 $)
from the shape of an array. For example, an array of shape $ (1, 3, 1) $ becomes
$ (3,) $ after squeezing. 

In [ ]:
# Create array with shape (1, 3, 1, 2):
A = np.array([[[[1, 2]], [[3, 4]], [[5, 6]]]])
print(A.shape)  # (1, 3, 1, 2)

# Remove single-dimensional axes:
B = A.squeeze()
print(B.shape)  # (3, 2)

Some key characteristics of `squeeze`:
* It returns a view of the input array, not a copy.
* Without arguments, it removes all single-dimensional axes.
* With the axis parameter, it can removes only specific single-dimensional axes.
* Raises a `ValueError` if you try to squeeze an axis of size $ > 1 $.

__Exercise:__ Squeeze out axis $ 2 $ of the array $ A $ in the preceding example to obtain
an array $ C $. Then modify an element of $ C $ and check whether $ A $ is affected.